# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{super_finder}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Didier Lafforgue"]
  s.date = %q{2010-04-07}
  s.description = %q{TextMate's "cmd-T" functionality in a web app}
  s.email = %q{didier@nocoffee.fr}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.textile",
     "Rakefile",
     "VERSION",
     "assets/images/boxy-ne.png",
     "assets/images/boxy-nw.png",
     "assets/images/boxy-se.png",
     "assets/images/boxy-sw.png",
     "assets/images/close.png",
     "assets/images/magnify.png",
     "assets/javascripts/boxy.js",
     "assets/javascripts/super_finder.js",
     "assets/stylesheets/boxy.css",
     "assets/stylesheets/super_finder.css",
     "init.rb",
     "install.rb",
     "lib/super_finder.rb",
     "lib/super_finder/cache_manager.rb",
     "lib/super_finder/cache_sweeper.rb",
     "lib/super_finder/config.rb",
     "lib/super_finder/filters.rb",
     "lib/super_finder/generator_controller.rb",
     "lib/super_finder/helper.rb",
     "lib/super_finder/initializer.rb",
     "lib/super_finder/routes.rb",
     "spec/assets/locales/en.yml",
     "spec/functional/cache_spec.rb",
     "spec/functional/controller_spec.rb",
     "spec/functional/functional_spec_helper.rb",
     "spec/functional/routes_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/unit/cache_manager_spec.rb",
     "spec/unit/config_spec.rb",
     "spec/unit/controller_spec.rb",
     "spec/unit/initializer_spec.rb",
     "spec/unit/unit_spec_helper.rb",
     "super_finder.gemspec",
     "tasks/super_finder_tasks.rake",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/did/super_finder}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{TextMate's "cmd-T" functionality in a web app}
  s.test_files = [
    "spec/functional/cache_spec.rb",
     "spec/functional/controller_spec.rb",
     "spec/functional/functional_spec_helper.rb",
     "spec/functional/routes_spec.rb",
     "spec/spec_helper.rb",
     "spec/unit/cache_manager_spec.rb",
     "spec/unit/config_spec.rb",
     "spec/unit/controller_spec.rb",
     "spec/unit/initializer_spec.rb",
     "spec/unit/unit_spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

